/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as FormsRouteImport } from './routes/forms'
import { Route as FocusRouteImport } from './routes/focus'
import { Route as EventsRouteImport } from './routes/events'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FormsFormIdRouteImport } from './routes/forms.$formId'
import { Route as FormIdRouteImport } from './routes/form.$id'
import { Route as EventsEventIdRouteImport } from './routes/events.$eventId'
import { Route as ApiAiGenerateRouteRouteImport } from './routes/api/ai/generate/route'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsRoute = FormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => rootRouteImport,
} as any)
const FocusRoute = FocusRouteImport.update({
  id: '/focus',
  path: '/focus',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsFormIdRoute = FormsFormIdRouteImport.update({
  id: '/$formId',
  path: '/$formId',
  getParentRoute: () => FormsRoute,
} as any)
const FormIdRoute = FormIdRouteImport.update({
  id: '/form/$id',
  path: '/form/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/$eventId',
  path: '/$eventId',
  getParentRoute: () => EventsRoute,
} as any)
const ApiAiGenerateRouteRoute = ApiAiGenerateRouteRouteImport.update({
  id: '/api/ai/generate',
  path: '/api/ai/generate',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/events': typeof EventsRouteWithChildren
  '/focus': typeof FocusRoute
  '/forms': typeof FormsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/form/$id': typeof FormIdRoute
  '/forms/$formId': typeof FormsFormIdRoute
  '/api/ai/generate': typeof ApiAiGenerateRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/events': typeof EventsRouteWithChildren
  '/focus': typeof FocusRoute
  '/forms': typeof FormsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/form/$id': typeof FormIdRoute
  '/forms/$formId': typeof FormsFormIdRoute
  '/api/ai/generate': typeof ApiAiGenerateRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/events': typeof EventsRouteWithChildren
  '/focus': typeof FocusRoute
  '/forms': typeof FormsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/form/$id': typeof FormIdRoute
  '/forms/$formId': typeof FormsFormIdRoute
  '/api/ai/generate': typeof ApiAiGenerateRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/events'
    | '/focus'
    | '/forms'
    | '/settings'
    | '/tasks'
    | '/events/$eventId'
    | '/form/$id'
    | '/forms/$formId'
    | '/api/ai/generate'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/events'
    | '/focus'
    | '/forms'
    | '/settings'
    | '/tasks'
    | '/events/$eventId'
    | '/form/$id'
    | '/forms/$formId'
    | '/api/ai/generate'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/events'
    | '/focus'
    | '/forms'
    | '/settings'
    | '/tasks'
    | '/events/$eventId'
    | '/form/$id'
    | '/forms/$formId'
    | '/api/ai/generate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  EventsRoute: typeof EventsRouteWithChildren
  FocusRoute: typeof FocusRoute
  FormsRoute: typeof FormsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  TasksRoute: typeof TasksRoute
  FormIdRoute: typeof FormIdRoute
  ApiAiGenerateRouteRoute: typeof ApiAiGenerateRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms': {
      id: '/forms'
      path: '/forms'
      fullPath: '/forms'
      preLoaderRoute: typeof FormsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/focus': {
      id: '/focus'
      path: '/focus'
      fullPath: '/focus'
      preLoaderRoute: typeof FocusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/$formId': {
      id: '/forms/$formId'
      path: '/$formId'
      fullPath: '/forms/$formId'
      preLoaderRoute: typeof FormsFormIdRouteImport
      parentRoute: typeof FormsRoute
    }
    '/form/$id': {
      id: '/form/$id'
      path: '/form/$id'
      fullPath: '/form/$id'
      preLoaderRoute: typeof FormIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof EventsRoute
    }
    '/api/ai/generate': {
      id: '/api/ai/generate'
      path: '/api/ai/generate'
      fullPath: '/api/ai/generate'
      preLoaderRoute: typeof ApiAiGenerateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EventsRouteChildren {
  EventsEventIdRoute: typeof EventsEventIdRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsEventIdRoute: EventsEventIdRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

interface FormsRouteChildren {
  FormsFormIdRoute: typeof FormsFormIdRoute
}

const FormsRouteChildren: FormsRouteChildren = {
  FormsFormIdRoute: FormsFormIdRoute,
}

const FormsRouteWithChildren = FormsRoute._addFileChildren(FormsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  EventsRoute: EventsRouteWithChildren,
  FocusRoute: FocusRoute,
  FormsRoute: FormsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  TasksRoute: TasksRoute,
  FormIdRoute: FormIdRoute,
  ApiAiGenerateRouteRoute: ApiAiGenerateRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
